name: Wikly
description: "A Simple Weekly Timetable Management App"
publish_to: 'none'
version: 1.0.0-beta
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  flutter_colorpicker: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  file_saver: ^0.2.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:
  build_web_compilers: ^4.2.4
  flutter_lints:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_foreground.png


flutter_native_splash:
  color: "#000000"
  color_dark: "#000000"
  image: assets/icons/icon_foreground.png
  image_dark: assets/icons/icon_foreground.png
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/icons/icon_foreground.png"
  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_background: "#000"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  ios: true
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/icons/icon_foreground.png"
    background_color: "#000"
    theme_color: "#000"

  windows:
    generate: true
    image_path: "assets/icons/icon_foreground.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icons/icon_foreground.png"

